name: Lint Code

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check Format
        run: npm run format:check

      - name: Lint Code
        run: npm run lint

      - name: Super Lint Code
        uses: super-linter/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_JSCPD: false
          # Why the ignorePattern in eslintrc.yml doesn't work?
          FILTER_REGEX_EXCLUDE: "(.github/workflows/tests.yml)|(.*dist/.*.js)"
          # https://github.com/super-linter/super-linter/issues/4023
          # And becuase of this issue, we have to exclude tests.yml above!
          # GITHUB_ACTIONS_COMMAND_ARGS: >-
          #   -ignore 'property "foo" is not defined in object type'
          #   -ignore 'property "bar" is not defined in object type'
          #   -ignore 'property "baz" is not defined in object type'
          #   -ignore 'property "qux" is not defined in object type'
