name: Test code

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm run ci-test

  test-simple:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: env
        with:
          files: ./src/test.env
          expand-vars: false
          export-vars: false
          strict: true
      - name: FOO is not exported
        run: |
          [[ -z $FOO ]]
          [[ "${{ steps.env.outputs.FOO }}" == "foo" ]]
      - name: BAR is nither exported nor expanded
        run: |
          [[ -z $BAR ]]
          [[ '${{ steps.env.outputs.BAR }}' == '$FOO' ]]
      - name: BAZ is nither exported nor expanded
        run: |
          [[ -z $BAZ ]]
          [[ '${{ steps.env.outputs.BAZ }}' == '$USER' ]]
      - name: QUX is nither exported nor expanded
        run: |
          [[ -z $QUX ]]
          [[ '${{ steps.env.outputs.QUX }}' == '$EXTERNAL_QUX' ]]

  test-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: env
        with:
          files: ./src/test.env
          expand-vars: false
          export-vars: true
          strict: true
      - name: FOO is exported
        run: |
          [[ "$FOO" == "foo" ]]
      - name: BAR is exported, but not expanded
        run: |
          [[ "$BAR" == '$FOO' ]]
      - name: BAZ is exported, but not expanded
        run: |
          [[ "$BAZ" == '$USER' ]]
      - name: QUX is exported, but not expanded
        run: |
          [[ "$QUX" == '$EXTERNAL_QUX' ]]

  test-expand-without-host-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: env
        with:
          files: ./src/test.env
          expand-vars: true
          export-vars: true
          ignore-host-env: true
          strict: false
      - name: FOO is exported
        run: |
          [[ "$FOO" == "foo" ]]
      - name: BAR is exported and expanded
        run: |
          [[ "$BAR" == "foo" ]]
      - name: BAZ is exported and expanded
        run: |
          [[ "$BAZ" == "" ]]
      - name: QUX is exported and expanded
        run: |
          [[ "$QUX" == "" ]]

  test-expand-with-host-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: env
        with:
          files: ./src/test.env
          expand-vars: true
          export-vars: true
          ignore-host-env: false
          strict: false
      - name: FOO is exported
        run: |
          [[ "$FOO" == "foo" ]]
      - name: BAR is exported and expanded
        run: |
          [[ "$BAR" == "foo" ]]
      - name: BAZ is exported and expanded
        run: |
          [[ "$BAZ" == "$USER" ]]
      - name: QUX is exported and expanded
        run: |
          [[ "$QUX" == "" ]]

  test-additional-vars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: env
        with:
          files: ./src/test.env
          expand-vars: true
          export-vars: true
          additional-vars: '${{ toJSON(vars) }}'
          strict: false
      - name: FOO is exported
        run: |
          [[ "$FOO" == "foo" ]]
      - name: BAR is exported and expanded
        run: |
          [[ "$BAR" == "foo" ]]
      - name: BAZ is exported and expanded
        run: |
          [[ "$BAZ" == "" ]]
      - name: QUX is exported and expanded
        run: |
          [[ "$QUX" == "qux" ]]
